### ISSUE TITLE
acclZ反転判定の閾値を調査

### ISSUE THREAD

**Issue by arahatashun** [arahatashun/cansat#2]
<0ではなくて適当な負の値にする

if(data.acclZ_scaled < 0)
	{
		printf("G:%f z_posture:reverse\n",data.acclZ_scaled);
		return -1;

**Comment by hirotaka912** [comment]
これacclZの値が擬似一様乱数状態なので無理です

**Comment by arahatashun** [comment]
statisticallyに妥当な値という意味です

**Comment by hirotaka912** [comment]
たすけて

**Comment by hirotaka912** [comment]
-0.8
