### ISSUE TITLE
通信距離試験

### ISSUE THREAD

**Issue by hirotaka912** [arahatashun/cansat#21]
xbeeでの通信距離最大を河川敷でやってないのでやる

**Comment by arahatashun** [comment]
アンテナ変えてないので再試験

**Comment by arahatashun** [comment]
iiym先生はXBEEで受信したデータを保存できるように設定する方法を調べてwikiに書いてください

**Comment by arahatashun** [comment]
shell scriptを書いてgithubにあげてください

**Comment by hirotaka912** [comment]
どんがgithubにあげてたやつは？
