### ISSUE TITLE
xbee購入

### ISSUE THREAD

**Issue by arahatashun** [arahatashun/cansat#24]
Xbee Pro S2C wire antenaをガーラック初日までに確実に調達すること

**Comment by arahatashun** [comment]
発送メール到着次第tracking ID ここにはって。
水曜日の昼に発送メールこなかったらchatで急かしてください

**Comment by hirotaka912** [comment]
俺関係なくね？

**Comment by arahatashun** [comment]
キャッジリターン
https://stackoverflow.com/questions/7812142/how-to-toggle-cr-lf-in-gnu-screen

**Comment by arahatashun** [comment]
どうなりましたか

**Comment by kdricemt** [comment]
\r\nのやつ？

2017年9月6日水曜日、Shun Arahata<notifications@github.com>さんは書きました:

**Comment by arahatashun** [comment]
soudayo
