### ISSUE TITLE
高度の計算式について

### ISSUE THREAD

**Issue by naoki-cpp** [arahatashun/cansat#28]
https://github.com/arahatashun/cansat/wiki/%E6%B0%97%E5%9C%A7%E3%82%BB%E3%83%B3%E3%82%B5%E3%83%BC%E3%81%AE%E9%AB%98%E5%BA%A6%E8%A8%88%E7%AE%97%E5%BC%8F%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6
に書いてある式ですが、
```
P/P_0
```
ではなく、 
```
P_0/P
```
ではないでしょうか？また、気象庁のサイトと書かれていますが、実際にはカシオのサイトになっています。

**Comment by arahatashun** [comment]
ご指摘ありがとうございます．二つのご指摘の点，ご指摘通りに思えますが，
書いた[本人](https://github.com/kdricemt)に聞いてます．

また，ARLISSの際は，wikiに載っている計算式ではなく，温度を使わず気圧だけから高度を計算したことを記憶しております．気圧だけから高度を計算するほうが信頼性が高いと判断しました．

**Comment by hirotaka912** [comment]
[本人](https://github.com/kdricemt)に聞いてみました．
naoki-cpp様のおっしゃる通り，ミスであるとのことです．
修正致しました．
